[project]
name = "cobrastyle-lightningcss"
version = "0.0.0.dev1"
description = "Python bindings for lightningcss"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]

[tool.uv]
dev-dependencies = [
    "maturin>=1.7.1",
    "pip>=24.2",
    "pytest>=8.3.2",
    "syrupy>=4.7.1",
]
